image: public.ecr.aws/bitnami/node:14

variables:
  KUBERNETES_CPU_REQUEST: 3
  KUBERNETES_CPU_LIMIT: 5
  KUBERNETES_MEMORY_REQUEST: 6Gi
  KUBERNETES_MEMORY_LIMIT: 8Gi
  KUBERNETES_EPHEMERAL_STORAGE_REQUEST: 512Mi
  KUBERNETES_EPHEMERAL_STORAGE_LIMIT: 1Gi

stages:
  - build
  - test
  - metadata

accelerator-build:
  stage: build
  script:
    - "export NODE_OPTIONS=--max_old_space_size=4096"
    - "cd source"
    - "npm install --global yarn"
    - "yarn install"
    - "yarn lint"
    - "yarn lerna link"
    - "yarn build"
    - "cd packages/@aws-accelerator/installer"
    - "yarn cdk synth"
    - "cp cdk.out/AWSAccelerator-InstallerStack.template.json $CI_PROJECT_DIR/AWSAccelerator-InstallerStack.template.json"
  artifacts:
    name: "installer-template"
    when: on_success
    paths:
      - AWSAccelerator-InstallerStack.template.json
accelerator-test:
  stage: test
  script:
    - "wget -v 'https://s3.amazonaws.com/viperlight-scanner/latest/viperlight.zip'"
    - "unzip -qo viperlight.zip -d ../viperlight"
    - "rm -r ./viperlight.zip"
    - "../viperlight/bin/viperlight scan"
  artifacts:
    untracked: true
    expire_in: 1 day
pages:
  stage: metadata
  script:
    - "export NODE_OPTIONS=--max_old_space_size=8192"
    - "cd source"
    - "yarn install"
    - "yarn docs"
    - "cp -R docs/ ../public/"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"