image: public.ecr.aws/bitnami/node:14


stages:
  - build
  - test
  - metadata

accelerator-build:
  stage: build
  tags:
    - arch:amd64
    - size:large
  script:
    - "export NODE_OPTIONS=--max_old_space_size=4096"
    - "cd source"
    - "npm install --global yarn"
    - "yarn install"
    - "yarn lint"
    - "yarn lerna link"
    - "yarn build"
    - "cd packages/@aws-accelerator/installer"
    - "yarn cdk synth"
    - "cp cdk.out/AWSAccelerator-InstallerStack.template.json $CI_PROJECT_DIR/AWSAccelerator-InstallerStack.template.json"
  artifacts:
    name: "installer-template"
    when: on_success
    paths:
      - AWSAccelerator-InstallerStack.template.json
accelerator-test:
  stage: test
  tags:
    - arch:amd64
    - size:large
  script:
    - "export NODE_OPTIONS=--max_old_space_size=4096"
    - "cd source"
    - "npm install --global yarn"
    - "yarn install"
    - "yarn lint"
    - "yarn lerna link"
    - "yarn build"
    - "yarn test"
    ## Temporary disabled viperlight till the issue fixed      
    # - "wget -v 'https://s3.amazonaws.com/viperlight-scanner/latest/viperlight.zip'"
    # - "unzip -qo viperlight.zip -d ../viperlight"
    # - "rm -r ./viperlight.zip"
    # - "../viperlight/bin/viperlight scan"
    - "echo Temporary disabled viperlight till the issue fixed"  
  artifacts:
    when: always
    reports:
      junit:
        - source/test-reports/*.xml
    expire_in: 1 day
pages:
  stage: metadata
  tags:
    - arch:amd64
    - size:large
  script:
    - "export NODE_OPTIONS=--max_old_space_size=8192"
    - "cd source"
    - "yarn install"
    - "yarn build"
    - "yarn docs"
    - "cp -R docs/ ../public/"
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
