---
# To start a well-planned OU structure in your landing zone,
# AWS Control Tower sets up a Security OU for you. This OU contains three
# shared accounts: the management (primary) account, the log archive account,
# and the security audit account (also referred to as the audit account).
mandatoryAccounts:
  - name: Management
    description: The management (primary) account
    email: <management-account>@example.com <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Root
  - name: Log Archive
    description: The log archive account
    email: <log-archive>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
  - name: Audit
    description: The security audit account (also referred to as the audit account)
    email: <audit>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
workloadAccounts:
  - name: Shared Network
    description: The shared network account (example)
    email: <shared-network>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Infrastructure
