mandatoryAccounts:
  - name: Management
    description: The management (primary) account
    email: <management-account>@example.com <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Root
  - name: Log Archive
    description: The log archive account
    email: <log-archive>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
  - name: Audit
    description: The security audit account (also referred to as the audit account)
    email: <audit>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Security
workloadAccounts:
  - name: Shared Services
    description: The Shared Services account
    email: <shared-services>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Infrastructure
  - name: Network
    description: The Network account
    email: <network>@example.com  <----- UPDATE EMAIL ADDRESS
    organizationalUnit: Infrastructure
