homeRegion: &HOME_REGION us-east-1
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: AWSControlTowerExecution
controlTower:
  enable: true
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
dataProtection:
  enable: true
  deploymentTargets:
    organizationalUnits:
      - Root
  identityPerimeter:
    enable: true
  resourcePerimeter:
    enable: true
  networkPerimeter:
    enable: true
reports:
  costAndUsageReport:
    compression: Parquet
    format: Parquet
    reportName: accelerator-cur
    s3Prefix: cur
    timeUnit: DAILY
    refreshClosedReports: true
    reportVersioning: CREATE_NEW_REPORT
