homeRegion: &HOME_REGION us-east-1
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: AWSControlTowerExecution
controlTower:
  enable: true
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
dataProtection:
  enable: true
  deploymentTargets:
    organizationalUnits:
      - Root
  identityPerimeter:
    enable: true
  resourcePerimeter:
    enable: true
  networkPerimeter:
    enable: true
reports:
  costAndUsageReport:
    compression: Parquet
    format: Parquet
    reportName: accelerator-cur
    s3Prefix: cur
    timeUnit: DAILY
    refreshClosedReports: true
    reportVersioning: CREATE_NEW_REPORT
  budgets:
    budgetName: accel-budget
    timeUnit: MONTHLY
    budgetType: COST
    amount: 2000
    includeUpfront: true
    includeTax: true
    includeSupport: true
    includeSubscription: true
    includeRecurring: true
    includeOtherSubscription: true
    includeDiscount: true
    includeCredit: false
    includeRefund: false
    useBlended: false
    useAmortized: false
    subscriptionType: EMAIL
    address: myemail+pa-budg@example.com
    unit: USD
    notification:
      notificationType: ACTUAL
      thresholdType: PERCENTAGE
      threshold: 90
      comparisonOperator: GREATER_THAN
      
