home-region: &HOME_REGION us-east-1
enabled-regions:
  - *HOME_REGION
control-tower:
  enable: true
logging:
  account: log-archive
  s3-access-logs:
    enable: true
    exclude-regions: []
    exclude-accounts: []
    organizational-units:
      - Root
    accounts: []
  cloudtrail:
    enable: true
    organization-trail: true