homeRegion: &HOME_REGION us-east-1
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: AWSControlTowerExecution
cloudwatchLogRetentionInDays: 3653
controlTower:
  enable: true
logging:
  account: LogArchive
  cloudtrail:
    enable: false
    organizationTrail: false
  sessionManager:
    sendToCloudWatchLogs: false
    sendToS3: true
  accessLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 1
        expiration: 1825
        expiredObjectDeleteMarker: false
        id: AccessLogBucketLifecycleRule
        transitions:
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
        noncurrentVersionTransitions:
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
        noncurrentVersionExpiration: 366
  centralLogBucket:
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 1
        expiration: 1825
        expiredObjectDeleteMarker: false
        id: CentralLogBucketLifecycleRule
        transitions:
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
        noncurrentVersionTransitions:
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
        noncurrentVersionExpiration: 366
dataProtection:
  enable: true
  deploymentTargets:
    organizationalUnits:
      - Root
  identityPerimeter:
    enable: true
  resourcePerimeter:
    enable: true
  networkPerimeter:
    enable: true
reports:
  costAndUsageReport:
    compression: Parquet
    format: Parquet
    reportName: accelerator-cur
    s3Prefix: cur
    timeUnit: DAILY
    refreshClosedReports: true
    reportVersioning: CREATE_NEW_REPORT
    lifecycleRules:
      - enabled: true
        abortIncompleteMultipartUpload: 1
        expiration: 1825
        expiredObjectDeleteMarker: false
        id: CostAndUsageLifecycleRule
        transitions:
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
        noncurrentVersionTransitions:
          - storageClass: DEEP_ARCHIVE
            transitionAfter: 365
        noncurrentVersionExpiration: 366
  budgets:
    - name: accel-budget
      timeUnit: MONTHLY
      type: COST
      amount: 2000
      includeUpfront: true
      includeTax: true
      includeSupport: true
      includeSubscription: true
      includeRecurring: true
      includeOtherSubscription: true
      includeDiscount: true
      includeCredit: false
      includeRefund: false
      useBlended: false
      useAmortized: false
      unit: USD
      notifications:
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 100
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: myemail+pa-budg@example.com
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 90
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: myemail+pa-budg@example.com
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 80
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: myemail+pa-budg@example.com
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 75
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: myemail+pa-budg@example.com
        - type: ACTUAL
          thresholdType: PERCENTAGE
          threshold: 50
          comparisonOperator: GREATER_THAN
          subscriptionType: EMAIL
          address: myemail+pa-budg@example.com
