homeRegion: &HOME_REGION us-east-1
enabledRegions:
  - *HOME_REGION
managementAccountAccessRole: 'AWSControlTowerExecution'
controlTower:
  enable: true
logging:
  account: Log Archive
  cloudtrail:
    enable: false
    organizationTrail: false
