policy-sets:
  - organizational-units:
      - root-ou
    policies:
      - name: Default-Boundary-Policy
        policy: boundary-policy.json
role-sets:
  - organizational-units:
      - root-ou
    roles:
      - name: EC2-Default-SSM-AD-Role
        assumed-by:
          type: service
          principal: ec2.amazonaws.com
        policies:
          aws-managed:
            - AmazonSSMManagedInstanceCore
            - AmazonSSMDirectoryServiceAccess
            - CloudWatchAgentServerPolicy
        boundary-policy: Default-Boundary-Policy
group-sets:
  - organizational-units:
      - root-ou
    groups:
      - name: Administrators
        policies:
          aws-managed:
            - AdministratorAccess
user-sets:
  - accounts:
      - management
    users:
      - username: breakGlassUser01
        group: Administrators
        boundary-policy: Default-Boundary-Policy
      - username: breakGlassUser02
        group: Administrators
        boundary-policy: Default-Boundary-Policy
