enable: true
organizationalUnits:
  - name: Security
    path: /
  - name: Infrastructure
    path: /
  - name: Policy Staging
    path: /
  - name: Suspended
    path: /
  - name: Sandbox
    path: /
  - name: Dev
    path: /
  - name: Test
    path: /
  - name: Prod
    path: /
quarantineNewAccounts:
    enable: true
    scpPolicyName: QuarantineAccounts
serviceControlPolicies:
  - name: DenyDeleteVpcFlowLogs
    description: >
      This SCP prevents users or roles in any affected account from deleting
      Amazon Elastic Compute Cloud (Amazon EC2) flow logs or CloudWatch log
      groups or log streams.
    policy: service-control-policies/deny-delete-vpc-flow-logs.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Security
  - name: QuarantineAccounts
    description: >
      This SCP is used to prevent changes to new accounts until the accelerator
      has been executed successfully.
      This policy will be applied upon account creation if enabled.
    policy: service-control-policies/quarantine.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits: []
taggingPolicies:
  - name: TagPolicy
    description: Organization Tagging Policy
    policy: tagging-policies/org-tag-policy.json
    deploymentTargets:
        organizationalUnits:
          - Root
backupPolicies:
  - name: BackupPolicy
    description: Organization Backup Policy
    policy: backup-policies/org-backup-policies.json
    deploymentTargets:
        organizationalUnits:
          - Root