organizationsAccessRole: 'AWSControlTowerExecution'
organizationalUnits:
  - name: Security
    parent: Root
  - name: Sandbox
    parent: Root
serviceControlPolicies:
  - name: DenyDeleteVpcFlowLogs
    description: >
      This SCP prevents users or roles in any affected account from deleting
      Amazon Elastic Compute Cloud (Amazon EC2) flow logs or CloudWatch log
      groups or log streams.
    policy: deny-delete-vpc-flow-logs.json
    type: customerManaged
    deploymentTargets:
      organizationalUnits:
        - Security
